build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,7 +13,7 @@ jobs:
     steps:
       - uses: actions/checkout@v4
         with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+          fetch-depth: 0
 
       - name: Set up JDK 17
         uses: actions/setup-java@v1
@@ -43,13 +43,25 @@ jobs:
           New-Item -Path .\.sonar\scanner -ItemType Directory
           dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
 
+      - name: Test SonarQube Server Connection
+        shell: powershell
+        run: |
+          $url = "${{ secrets.SONAR_HOST_URL }}/api/server/version"
+          Write-Host "Testing connection to SonarQube server at $url"
+          try {
+            $response = Invoke-WebRequest -Uri $url
+            Write-Host "Connection successful. Server version: $($response.Content)"
+          } catch {
+            Write-Error "Failed to connect to SonarQube server at $url"
+            exit 1
+          }
+
       - name: Build and analyze
         shell: powershell
         run: |
           Write-Host "Starting SonarQube analysis..."
-          .\.sonar\scanner\dotnet-sonarscanner begin /k:"iotedge" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
+          .\.sonar\scanner\dotnet-sonarscanner begin /key:"iotedge" -d:sonar.token="${{ secrets.SONAR_TOKEN }}" -d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
           
-          $LASTEXITCODE = $?
           if ($LASTEXITCODE -ne 0) {
             Write-Error "SonarQube scanner failed to start with exit code $LASTEXITCODE"
             exit $LASTEXITCODE
@@ -58,7 +70,6 @@ jobs:
           Write-Host "Building the project..."
           dotnet build > build.log
           
-          $LASTEXITCODE = $?
           if ($LASTEXITCODE -ne 0) {
             Write-Error "dotnet build failed with exit code $LASTEXITCODE"
             Get-Content -Path .\build.log | ForEach-Object { Write-Host $_ }
@@ -68,7 +79,6 @@ jobs:
           Write-Host "Completing SonarQube analysis..."
           .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
           
-          $LASTEXITCODE = $?
           if ($LASTEXITCODE -ne 0) {
             Write-Error "SonarQube analysis failed with exit code $LASTEXITCODE"
             Get-Content -Path .\build.log | ForEach-Object { Write-Host $_ }
